INT
VARCHAR(100)
CHAR(10)
DECIMAL(10,2)
DATE
DATETIME
BIT

SELECT GETDATE();

SELECT YEAR(GETDATE());

SELECT MONTH(GETDATE());

SELECT DAY(GETDATE());

SELECT DATEADD(DAY, 7, GETDATE());

SELECT DATEDIFF(YEAR, '2000-01-01', GETDATE());

SELECT UPPER('codetribe');

SELECT LOWER('CODETRIBE');

SELECT LEN('CodeTribe');

SELECT LEFT('CodeTribe', 4);

SELECT RIGHT('CodeTribe', 5);

SELECT CONCAT('Code', ' ', 'Tribe');

SELECT SUBSTRING('CodeTribe', 1, 4);

SELECT REPLACE('CodeTribe', 'Code', 'Tech');